### ISSUE TITLE
Can not compile. Wrong OpenCV version?

### ISSUE THREAD

**Issue by lumsrouge** [antoinetlc/reflectance_maps#2]
Hi,
I am very interested by the work you have done here!
I would like to try using it, but I can not compile it.

I am using Qt Creator 4.7.2 (Community).
I downloaded the Opencv version you used: 2.4.11
Also placed the files at the same location indicated in your .pro file.

But without success.
I have a ton of errors about some "undefined references". eg "undefined references to `cv::fastFree(void*)`"
I googled thoses, and found some people that where using wrong version of opencv (like trying to use classes from 3.0 version when using 2.4)
Could that be the case here?

In order to open the project, I opened QtCreator and then, clicked on "Open new project", then went straight to double-clicked the "reflectance_maps.pro" file. Maybe is there an other/better way to open it?

I tried compiling it inside QTCreator using Mingw, did you use the same compiler?

If you have suggestions about what I might be doing wrong, please tell me!

**Comment by antoinetlc** [comment]
Hi,

Thanks for being interested in this work!
This is the right way of opening the pro file. I used the compiler msvc 2013 64 bits and not MinGW.
If I remember correctly by default the precompiled versions of OpenCV are compiled with MSVC on windows. For MinGW you probably have to compile OpenCV yourself.

Besides you have to change the pro file to the correct path where OpenCV is compiled on your machine. These are the following lines :
 
        
         `INCLUDEPATH += "C:\\OpenCV2411\\build\\include"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_core2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_highgui2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_imgproc2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_features2d2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_calib3d2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_contrib2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_flann2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_gpu2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_legacy2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ml2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_nonfree2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_objdetect2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ocl2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_photo2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_stitching2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_superres2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ts2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_video2411.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_videostab2411.lib"

         INCLUDEPATH += "C:\\OpenCV2411\\build\\include"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_core2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_highgui2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_imgproc2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_features2d2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_calib3d2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_contrib2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_flann2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_gpu2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_legacy2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ml2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_nonfree2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_objdetect2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ocl2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_photo2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_stitching2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_superres2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_ts2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_video2411d.lib"
         LIBS += "C:\\OpenCV2411\\build\\x64\\vc12\\lib\\opencv_videostab2411d.lib"
 `

You should change the paths to where your OpenCV is extracted. For instance : 

`INCLUDEPATH += "C:\\PathToYourOpenCV\\build\\include"
And so on...
 `

Note that the vc12 folder in OpenCV means the version precompiled with MSVC 2013. You might have to change it to mingw.

Sorry for not making the compilation very user friendly!
Hope that helps!

**Comment by lumsrouge** [comment]
Hey!
Thank you very much for the answer, it does help!
I didn't know the library had to be compiled with the same compiler I used to compile the code.

I finally succeed to make it compile! (after lots of failed attempts ^^)

So, I'm currently trying to make it work and I have a few questions about it:

- How should be formatted the path I have to give to computeMaps? I am used to a linux environement, so I do not now if I should write it with '/' , '\' or '\\' ...
- I saw that your program try to open files that do not start with IMG_1.PNG or IMG_2.PNG, ...? but with IMG_2856.PNG, IMG_2857.PNG ... why is that?
- I know this is not your role, but could you help me find how to print on standard output?
I am trying to use :
cout << "Some text"; 

But it isn't working, I have no printing in the output panel inside QtCreator. Also nothing when running it from console or PowerShell ...

Thank you for helping me :)

**Comment by antoinetlc** [comment]
Hey!

I am glad you managed to make it compile. I think the program should be working on Linux if you prefer this environment but I have not tested it.

1.  I think '/' should work well on Linux and windows but to be sure you should print the path of the images that are loaded in the console using 'cout'. 

For instance if inside your application folder you have : 

- executable file
- 'images' folder that contains the images

The path that you send to computeMaps is simply 'images' or the absolute path to the images folder.

2. You will have to change the image number for your application. In my case I used IMG_2856.JPG because it was the name given by the camera but you will have to change it to load your images. Sorry if all that is hardcoded I did not have much time to open source it.

3. Usually QtCreator opens a terminal or write the text to the application console below the code (where the compilation errors appear). 

If you cannot see the console I can see two ways of fixing this : 

* You can go in the .pro file and delete the first two lines ` QT += core gui
QT += opengl` and replace them with `CONFIG += console`. Then you can run 'qmake' (right click on the pro file in QtCreator) and then recompile. The project was originally extracted from another OpenGL application and I forgot to change that.

If this does not work either you can try the following : create a new C++ console project in QtCreator and check that the by default 'Hello World' code appears. Then import the files into this new project and recompile.

Hope it works :)
